### ISSUE TITLE
Scroll / zoom issue

### ISSUE THREAD

**Issue by JetGum** [GiovanniSalmeri/yellow-openstreetmap#5]
Dear Giovanni,

first of all, thanks for this wonderful implementation of OSM into a Yellow extension. Comes in very handy for one of my websites, which gives regional info on diverse locations.

What's the issue, then? 

I noticed an odd behaviour: When I scroll down my website with a map included, the OSM iframe begins to zoom out in 4 clearly visible steps when the mouse is inside the iframe. I know that zooming in/out is a standard feature of OSM, but is there a way to eliminate the zooming altogether and/or providing a static image, maybe linked to the OSM website?

Cheers,

Carsten

**Comment by JetGum** [comment]
Dear Giovanni,

ups, my bad.... I changed your extension code a bit to make the iframe responive along the CSS solution proposed [here](https://www.w3schools.com/howto/howto_css_responsive_iframes.asp), and forgot the "map" class. If I add that to the iframe container class, the abovementioned behaviour is gone.

Cheers, Carsten

**Comment by GiovanniSalmeri** [comment]
@JetGum I'm glad that all is working now :-) Just for information: I have checked the code (written some time ago) and I have seen that the purpose of that `map` class is to offer to JS a way to distinguish the maps and to modify only for them the behaviour of the mouse. Anyway I will check as soon as possible the page you have linked, perhaps it would be useful to modify in that sense the extension? Cheers, Giovanni

**Comment by JetGum** [comment]
@GiovanniSalmeri Looking forward to the reponsiveness! Cheers, Carsten
